#!/bin/sh

if [ "$1" = "hi" ] || [ "$1" = "hello" ]; then
	echo 'The first argument was "hi"'
elif [ "$1" = "bye" ]
	then
	echo 'The first argument was "bye"'
else
	echo 'The first argument was neither "hi" nor "hello" or "bye"'
fi

case $1 in
	hi|hello)
		echo 'Fine, hi or hello'
		;;
	bye)
		echo 'Fine, bye'
		;;
	*)
		echo 'Default case was reached'
		;;
esac

for str in one two three four; do
	echo $str
done