#!/bin/sh

######################################################################
# if/else/elif #######################################################

if [ "$1" = "hi" ] || [ "$1" = "hello" ]; then
	echo 'The first argument was "hi"'
elif [ "$1" = "bye" ]
	then
	echo 'The first argument was "bye"'
else
	echo 'The first argument was neither "hi" nor "hello" or "bye"'
fi

######################################################################
# case ###############################################################

case $1 in
	hi|hello)
		echo 'Fine, hi or hello'
		;;
	bye)
		echo 'Fine, bye'
		;;
	*)
		echo 'Default case was reached'
		;;
esac

######################################################################
# for ################################################################

for str in one two three four; do
	echo $str
done

######################################################################
# while ##############################################################

FILE=./whiletest;
echo firstline > $FILE

while tail -10 $FILE | grep -q firstline; do
	echo -n "Number of lines in $FILE: "
	wc -l $FILE | awk '{print $1}'

	echo "newline" >> $FILE
done

rm -f $FILE
